language: ruby

rvm:
  - 2.1.1
  - 2.2.2
  - ruby-head
  - jruby-19mode
  - rbx-2

matrix:
  allow_failures:
    - rvm: rbx-2

gemfile:
  - Gemfile

services:
  - mongodb

env: CI="travis"

script: "bundle exec rspec"
